default: &default
  adapter: postgresql
  username: davidhenry

development:
  <<: *default
  database: co_aker

test:
  <<: *default
  database: co_aker_test

production:
  url: <%= ENV["DATABASE_URL"] %>
